### ISSUE TITLE
Irene has crashed after timer  ends

### ISSUE THREAD

**Issue by colesnicov** [janvarev/Irene-Voice-Assistant#56]
Добрый вечер. Интересный проект, с 50% работает. Вот только:

- Включу Ирину и попрошу включить тимер (время неважно, все равно упадёт).
- Потом с ней поздороваюсь: Ирина привет. 
- Она мене ответить.
- И всё..  

иду себе делать чтото своё но тимер никогда непрозвучал.  

```
denis@denis-OMEN:~/opt/Irene-Voice-Assistant-master$ python3  ./runva_vosk.py  
LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=10 max-active=3000 lattice-beam=2
LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components.
LOG (VoskAPI:ReadDataFiles():model.cc:248) Loading i-vector extractor from model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:282) Loading HCL and G from model/graph/HCLr.fst model/graph/Gr.fst
LOG (VoskAPI:ReadDataFiles():model.cc:308) Loading winfo model/graph/phones/word_boundary.int
################################################################################
Press Ctrl+C to stop the recording
################################################################################
JAA.PY v2.2.0 class created!
{'альбина': 'чатгпт'}
JAA PLUGIN: Core plugin 4.2 (core) started!
JAA PLUGIN: PlayWav through console 1.0 (plugin_playwav_consolewav) started!
JAA PLUGIN: Привет 1.0 (plugin_greetings) started!
JAA PLUGIN: Дата и время 1.2 (plugin_datetime) started!
JAA PLUGIN: Таймер 1.2 (plugin_timer) started!
JAA PLUGIN: Погода (wttr.in) 1.1 (plugin_weather_wttr) started!
JAA PLUGIN: TTS pyttsx 1.1 (plugin_tts_pyttsx) started!
JAA PLUGIN: Яндекс Расписания 1.0 (plugin_yandex_rasp) started!
JAA PLUGIN: Болталка с ChatGPT с сохранением контекста через Vsegpt.ru или другой OpenAI сервер 3.0 (plugin_boltalka_vsegpt) started!
JAA PLUGIN: Рандом 1.0 (plugin_random) started!
JAA PLUGIN: PlayWav through sounddevice 1.0 (plugin_playwav_sounddevice) started!
JAA PLUGIN: TTS console (for debug) 1.0 (plugin_tts_console) started!
JAA PLUGIN: PlayWav through simpleaudio 1.0 (plugin_playwav_simpleaudio) started!
JAA PLUGIN: Погода (open weather map) 1.1 (plugin_weatherowm) started!
JAA PLUGIN: TTS Elevenlabs 1.0 (plugin_tts_elevenlabs) started!
JAA PLUGIN ERROR: plugin_playwav_audioplayer error on load: Namespace Gst not available
Traceback (most recent call last):
 File "/home/denis/opt/Irene-Voice-Assistant-master/jaa.py", line 94, in init_plugin
   mod = self.import_plugin("plugins."+modname)
 File "/home/denis/opt/Irene-Voice-Assistant-master/jaa.py", line 174, in import_plugin
   __import__(module_name)
 File "/home/denis/opt/Irene-Voice-Assistant-master/plugins/plugin_playwav_audioplayer.py", line 7, in <module>
   from audioplayer import AudioPlayer
 File "/home/denis/.local/lib/python3.10/site-packages/audioplayer/__init__.py", line 12, in <module>
   from .audioplayer_linux import AudioPlayerLinux as AudioPlayer
 File "/home/denis/.local/lib/python3.10/site-packages/audioplayer/audioplayer_linux.py", line 8, in <module>
   gi.require_version('Gst', '1.0')
 File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
   raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gst not available
JAA PLUGIN: TTS silero V3 2.0 (plugin_tts_silero_v3) started!
JAA PLUGIN: MPC-HC проигрывание мультиков/сериалов 3.0 (plugin_mpchcmult) started!
JAA PLUGIN: TTS silero V4 2.0 (plugin_tts_silero_v4) started!
JAA PLUGIN: TTS vosk 1.3 (plugin_tts_vosk) started!
JAA PLUGIN: PlayWav through aplay 1.0 (plugin_playwav_aplay) started!
JAA PLUGIN: Игра больше меньше 1.0 (plugin_gamemoreless) started!
JAA PLUGIN: Команды управления мультимедия 1.2 (plugin_mediacmds) started!
JAA PLUGIN: vasisualy plugins loader 1.0 (plugin_vasi) started!
VoiceAssistantCore v10.9.0: run OFFLINE
TTS engines: pyttsx, console, elevenlabs, silero_v3, silero_v4, vosk
PlayWavs engines: consolewav, sounddevice, simpleaudio, aplay
FuzzyProcessor engines:  
Assistant names: ирина, ирины, ирину, дима
Commands list: #################################################################
plugin_greetings: привет|доброе утро
plugin_datetime: дата, время
plugin_timer: поставь таймер|поставь тайгер|таймер|тайгер
plugin_yandex_rasp: ближайший поезд|электричка|электрички
plugin_boltalka_vsegpt: поболтаем|поговорим, справка
plugin_random: подбрось|брось
plugin_mpchcmult: запусти плеер, мультик, сериал, стоп мультик|останови мультик
plugin_gamemoreless: игра больше меньше
plugin_mediacmds: пауза|паузу, дальше|вперед|вперёд, назад, стоп, без звука|выключи звук|со звуком|без мука, тише, громче, чуть тише, чуть громче, сильно тише, сильно громче, выключи плеер|закрой плеер, пробел
################################################################################
Input (cmd):  ирина таймер две минуты
New Timer ID = 0  curtime= 2024-04-13 18:35:05 duration= 120 endtime= 2024-04-13 18:37:05
Input (cmd):  ирина привет
- Сейчас я скажу фразу Рада тебя видеть!...
Если вы её не услышите, значит, у вас проблемы с TTS или выводом звука и их надо настроить через менеджер настроек.
- Я сказала фразу Рада тебя видеть!
End Timer ID = 0  curtime= 2024-04-13 18:37:05 endtime= 2024-04-13 18:37:05
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
denis@denis-OMEN:~/opt/Irene-Voice-Assistant-master$

```

Да, и Ирина упадёт аж когда истечёт желаемое время...

**Comment by e-ginger** [comment]
У меня возникла та же ошибка при окончании таймера:
`ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)`

Возникает она в plugin_sounddevice.py

**Comment by e-ginger** [comment]
После окончания таймера играет wav-файл, указанный в настройках. Вывод через sounddevice.

В коде плагина plugin_playwav_sounddevice.py есть строчка, которая читает данные файла:
```
data_set, fsample = sound_file.read(filename, dtype = 'float32')
```

И прочитанные данные почему-то в двумерном массиве:
```
array([[ 1.4426708e-03,  5.9008598e-04],
       ...,
       [ 2.3360252e-03, -4.8124790e-04]], dtype=float32)
```

А массив zeros, которыми его дальше дополняют, одномерный. вот:
```
array([0., 0., 0., ..., 0., 0., 0.])
```

Поэтому дальше `numpy.concatenate((data_set,zeros))` выдает ошибку и все падает.

**Comment by colesnicov** [comment]
У меня нет времени с этим играться и я даже не хочу. Но исправить это надо. Незнаю почему автор это не исправит..

**Comment by janvarev** [comment]
Решено в 10.9.4
