### ISSUE TITLE
ModuleNotFoundError: No module named '_socket'`

### ISSUE THREAD

**Issue by hardway777** [janvarev/Irene-Voice-Assistant#57]
```

Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_internal\cli\req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 182, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 228, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 290, in __init__
    super().__init__(
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 222, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 301, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_internal\operations\prepare.py", line 525, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_internal\operations\prepare.py", line 640, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_internal\operations\prepare.py", line 71, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_internal\distributions\sdist.py", line 54, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_internal\distributions\sdist.py", line 124, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_internal\distributions\sdist.py", line 101, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_internal\utils\misc.py", line 745, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "C:\Users\vovap\AppData\Roaming\Python\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\vovap\AppData\Local\Temp\pip-build-env-shyv3cry\overlay\Lib\site-packages\setuptools\__init__.py", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
  File "C:\Users\vovap\AppData\Local\Temp\pip-build-env-shyv3cry\overlay\Lib\site-packages\_distutils_hack\override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "C:\Users\vovap\AppData\Local\Temp\pip-build-env-shyv3cry\overlay\Lib\site-packages\_distutils_hack\__init__.py", line 70, in do_override
    ensure_local_distutils()
  File "C:\Users\vovap\AppData\Local\Temp\pip-build-env-shyv3cry\overlay\Lib\site-packages\_distutils_hack\__init__.py", line 56, in ensure_local_distutils
    core = importlib.import_module('distutils.core')
  File "importlib\__init__.py", line 126, in import_module
  File "C:\Users\vovap\AppData\Local\Temp\pip-build-env-shyv3cry\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 14, in <module>
    from .config import PyPIRCCommand
  File "C:\Users\vovap\AppData\Local\Temp\pip-build-env-shyv3cry\overlay\Lib\site-packages\setuptools\_distutils\config.py", line 7, in <module>
    import email.message
  File "email\message.py", line 15, in <module>
  File "email\utils.py", line 29, in <module>
  File "socket.py", line 51, in <module>
ModuleNotFoundError: No module named '_socket'
```

**Comment by janvarev** [comment]
Где-то проблемы с установкой нужных pip пакетов, это не проблема Ирины.
